// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate/db pull/studio) must use a DIRECT, non-pgbouncer
    // connection — the transaction pooler (:6543) breaks the schema engine with
    // `prepared statement "s1" already exists`. DIRECT_URL is Supabase's session
    // pooler (:5432). This file is CLI-only; the app runtime connects via
    // DATABASE_URL (:6543) in src/config/database.js.
    url: process.env["DIRECT_URL"],
  },
});
